#!/bin/bash

if [ "$DOCKER_TAG" == 'latest' ]; then
  s_version='master'
else
  s_version="$DOCKER_TAG"
fi

build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
version=$(git describe --tags 2> /dev/null || echo "$SOURCE_BRANCH")
vcs_ref=$(git rev-parse --short HEAD)

docker build \
  --build-arg BUILD_DATE="$build_date"         \
  --build-arg SINGULARITY_VERSION="$s_version" \
  --build-arg VCS_REF="$vcs_ref"               \
  --build-arg VERSION="$version"               \
  -t "$IMAGE_NAME" .
